services:
  pg_dev:
    build: .
    container_name: audb_test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: audb_test
    ports:
      - "5454:5432"
    volumes:
      - .:/audbExtension
